### ISSUE TITLE
rspec test generator broken by terraspace 2.2.7 release (worked in 2.2.6)

### ISSUE THREAD

**Issue by alexjfisher** [boltops-tools/rspec-terraspace#11]
With latest terraspace and terraspace-rspec releases (2.2.7 and 0.3.2) `bundle exec terraspace new test my_stack --type stack` is broken.

```
/home/alex/.rvm/gems/ruby-3.1.2/gems/rspec-terraspace-0.3.2/lib/templates/stack/test/Gemfile.tt:4:in `template': undefined method `build_gemfile'
```

The `build_gemfile` helper still in use by rspec-terraspace [here](https://github.com/boltops-tools/rspec-terraspace/blob/6deb6e7c3e48e94b785d52f2e34ad02ba3ec11bd/lib/templates/stack/test/Gemfile.tt#L4) (and [here](https://github.com/boltops-tools/rspec-terraspace/blob/6deb6e7c3e48e94b785d52f2e34ad02ba3ec11bd/lib/templates/module/test/Gemfile.tt#L4)) was removed in refactor done in https://github.com/boltops-tools/terraspace/pull/312

Thanks,
Alex

**Comment by alexjfisher** [comment]
Seems simple enough to fix.  I'll knock up a PR.
