### PR TITLE
Fix compatibility with latest `terraspace`

### LINKED ISSUE #11: rspec test generator broken by terraspace 2.2.7 release (worked in 2.2.6)
With latest terraspace and terraspace-rspec releases (2.2.7 and 0.3.2) `bundle exec terraspace new test my_stack --type stack` is broken.

```
/home/alex/.rvm/gems/ruby-3.1.2/gems/rspec-terraspace-0.3.2/lib/templates/stack/test/Gemfile.tt:4:in `template': undefined method `build_gemfile'
```

The `build_gemfile` helper still in use by rspec-terraspace [here](https://github.com/boltops-tools/rspec-terraspace/blob/6deb6e7c3e48e94b785d52f2e34ad02ba3ec11bd/lib/templates/stack/test/Gemfile.tt#L4) (and [here](https://github.com/boltops-tools/rspec-terraspace/blob/6deb6e7c3e48e94b785d52f2e34ad02ba3ec11bd/lib/templates/module/test/Gemfile.tt#L4)) was removed in refactor done in https://github.com/boltops-tools/terraspace/pull/312

Thanks,
Alex

### PR DESCRIPTION
**Pull request by alexjfisher**
Fixes #11

### CODE REVIEW

File: lib/templates/module/test/Gemfile.tt [hunk 1]
```diff
@@ -1,9 +1,5 @@
 source "https://rubygems.org"
 
-<%=
-build_gemfile(
```
Comment (alexjfisher) [inline lib/templates/module/test/Gemfile.tt:4]: This helper went in terraspace 2.2.7

File: lib/templates/module/test/Gemfile.tt [hunk 2]
```diff
@@ -1,9 +1,5 @@
...
-  "terraspace",
-  "rspec-terraspace",
-  plugin_gem_name,
-)
-%>
+gem "terraspace", "~> <%= terraspace_minor_version %>"
```
[the remark this answers is not in the document]
Comment (tongueroo) [reply lib/templates/module/test/Gemfile.tt:3]: Yup. To avoid the circular dependency, terraspace is not in the gemspec. It's only in the Gemfile for development. https://github.com/boltops-tools/rspec-terraspace/blob/6deb6e7c3e48e94b785d52f2e34ad02ba3ec11bd/Gemfile#L10

**Comment by tongueroo** [comment]
Thanks 👍 Released in rspec-terraspace 0.3.3
